id: PA2C75345
initial_creation_type: input
source_metadata:
  title: Chokling Tersar Series
  language: zh
  description: 'Texts related to the Chokling Tersar (mchog gling gter gsar), the
    New Treasures of Chokgyur Lingpa (1829–1870):'
  volume:
    4c663d11f1d7452f95dee28b0f0182a0:
      title: 'Advice on Nonsectarianism (from Radiant Sunlight of the Victorious Ones''
        Teachings: A Brief, First-Hand Account of the Liberating Life-Story of the
        Great Emanated Treasure Revealer)'
      parent: Advice
    4bded5cd15d047f19ebc0e8b603065c4:
      title: Pithy Advice on Checking One's Progress on the Path
      parent: Advice
    0b42ac2f4823474683f6398d0619c33a:
      title: The Aspiration of the Vajradhātu Maṇḍala
      parent: Aspiration Prayers
    6447791d72f349a5bc07cb998ff98b88:
      title: 'Radiant Sunlight of the Victors’ Teachings: A Brief, First-Hand Account
        of the Liberating Life-Story of the Great Emanated Treasure Revealer'
      parent: Biography
    9daa63afb0884a74b38b47800bc0aae2:
      title: 'The Wish-Fulfilling Tree: The Life Story of the Master of Uḍḍiyāna
        as found in Padmasambhava’s Sevenfold Cycle of Profundity'
      parent: Biography
    e232991c919a468781a4788681a4e2cd:
      title: Concise Offering of the Body from the Root Text of the Heart Accomplishment
        of the Guru Tukdrup, The Essential Manual of Oral Instructions (Shaldam Nyingjang)
      parent: Chöd
    f10da274853d4c1abc785f06fe7c3d2c:
      title: The Ornament of Padmasambhava’s Enlightened Vision
      parent: Commentaries
    8e36d7e61bf446559c3f030185c667fc:
      title: 'The Vajra Words Unveiled: A Commentary on the Düsum Sangyé Prayer to
        the Guru'
      parent: Commentaries
    d832898af8504d3382ea81449c78b446:
      title: The Lament of Rudra
      parent: Confession
    3bd47bcc555344a0a9a19bff0fba60c8:
      title: 'The Garland of Utpala Flowers: A Prayer to the Masters of the Lineage
        of Zabtik Drolchok'
      parent: Lineage Prayers
    412056b5ffc1408c83454fa503be7612:
      title: The Prayer Which Removes All Obstacles from the Path (Barché Lamsel)
      parent: Prayers
    7ddee188c9a74842abd8611be9c6b208:
      title: The Prayer in Six Vajra Lines
      parent: Prayers
    c47a5c18df85419ea1ec961f5a6d1240:
      title: 'The Prayer to Guru Rinpoche that Spontaneously Fulfils All Wishes (Sampa
        Lhundrupma) from The Guru’s Heart Practice: The Wish-Fulfilling Jewel'
      parent: Prayers
    b3e40f2f0a93400dad2b2888e27cad9f:
      title: The Testament Prayer to Orgyen Rinpoche
      parent: Prayers
    6e2c67fcfa804a739f429e111f7d100c:
      title: The Single-Page Practice of the Guru of Great Bliss
      parent: Sādhanas
    72a5bc742db842a08e847fcbdb61e3e5:
      title: Concise Daily Practice of Vajrasattva
      parent: Sādhanas
    e99e54f80b40416c90dd9b3e660e0c2c:
      title: Extremely Secret Unelaborate Daily Sādhana for the Heart Practice of
        the Great Demon-Slayer
      parent: Sādhanas
    5dbaf2ff69f7466ba2c04da5b2050079:
      title: White and Red Sur Offerings That Are Very Easy to Apply
      parent: Sur Offering
    5e421b3a460b45c0ae45a8de94ceaa37:
      title: Vajrakīla Tsok Prayer from Sangtik Korsum
      parent: Tsok
created_at: '2022-03-01T03:13:53.996384'
last_modified_at: '2022-03-01T03:13:53.996386'
